import { LiveChannel } from './channelService';

export const mockLiveChannels: LiveChannel[] = [
  {
    id: '1',
    name: 'BBC One',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/BBC_One_logo_2021.svg/512px-BBC_One_logo_2021.svg.png',
    category: 'Entertainment',
  },
  {
    id: '2',
    name: 'BBC Two',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/BBC_Two_logo_2021.svg/512px-BBC_Two_logo_2021.svg.png',
    category: 'Entertainment',
  },
  {
    id: '3',
    name: 'ITV',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/92/ITV_logo_2013.svg/1920px-ITV_logo_2013.svg.png',
    category: 'Entertainment',
  },
  {
    id: '4',
    name: 'Channel 4',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0e/Channel_4_logo_2015.svg/1024px-Channel_4_logo_2015.svg.png',
    category: 'Entertainment',
  },
  {
    id: '5',
    name: 'Sky Sports Main Event',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    logoUrl: 'https://www.skysports.com/assets/img/logos/sky-sports-logo.png',
    category: 'Sports',
  },
  {
    id: '6',
    name: 'Sky Sports Premier League',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    logoUrl: 'https://www.skysports.com/assets/img/logos/sky-sports-logo.png',
    category: 'Sports',
  },
  {
    id: '7',
    name: 'ESPN',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/ESPN_wordmark.svg/1920px-ESPN_wordmark.svg.png',
    category: 'Sports',
  },
  {
    id: '8',
    name: 'CNN',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/CNN.svg/1920px-CNN.svg.png',
    category: 'News',
  },
  {
    id: '9',
    name: 'BBC News',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/BBC_News_2019.svg/1920px-BBC_News_2019.svg.png',
    category: 'News',
  },
  {
    id: '10',
    name: 'Sky News',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/57/Sky_News_logo.svg/1920px-Sky_News_logo.svg.png',
    category: 'News',
  },
  {
    id: '11',
    name: 'Discovery Channel',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/2019_Discovery_logo.svg/1920px-2019_Discovery_logo.svg.png',
    category: 'Documentary',
  },
  {
    id: '12',
    name: 'National Geographic',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Natgeologo.svg/1024px-Natgeologo.svg.png',
    category: 'Documentary',
  },
  {
    id: '13',
    name: 'Disney Channel',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Disney_Channel_2014_HD.png/1920px-Disney_Channel_2014_HD.png',
    category: 'Kids',
  },
  {
    id: '14',
    name: 'Cartoon Network',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Cartoon_Network_2010_logo.svg/1920px-Cartoon_Network_2010_logo.svg.png',
    category: 'Kids',
  },
  {
    id: '15',
    name: 'Nickelodeon',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Nickelodeon_2009_logo.svg/1920px-Nickelodeon_2009_logo.svg.png',
    category: 'Kids',
  },
  {
    id: '16',
    name: 'MTV',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/MTV_Logo_2010.svg/1920px-MTV_Logo_2010.svg.png',
    category: 'Music',
  },
  {
    id: '17',
    name: 'VH1',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/VH1_logonew.svg/1920px-VH1_logonew.svg.png',
    category: 'Music',
  },
  {
    id: '18',
    name: 'Comedy Central',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Comedy_Central_2018.svg/1920px-Comedy_Central_2018.svg.png',
    category: 'Entertainment',
  },
  {
    id: '19',
    name: 'HBO',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/HBO_logo.svg/1920px-HBO_logo.svg.png',
    category: 'Movies',
  },
  {
    id: '20',
    name: 'Netflix',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Netflix_2015_logo.svg/1920px-Netflix_2015_logo.svg.png',
    category: 'Movies',
  },
];

export const mockCategories = [
  'Entertainment',
  'Sports',
  'News',
  'Documentary',
  'Kids',
  'Music',
  'Movies',
]; 